name: Daily update

on:
  schedule:
    - cron: '0 8 * * *'   # 8h UTC chaque jour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate content
        run: |
          python scripts/generate_content.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update $(date)" || exit 0
          git push
